services:
  webserver:
    image: nginx_web
    expose :
      - "80"
    networks:
      backend:
    volumes:
      - html:/opt/html/:ro
      - nginx/conf.d:/etc/nginx/conf.d:ro
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      ressources: 
        limits:
          cpus: '0.20'
          memory: 50M

  loadbalancer:
    image: gcc
    command: sleep 3000
    ports:
      - "8080:8080"
    networks:
      backend:
          ipv4_address: 192.168.4.2
      external_network:
    volumes:
      - ./loadbalancer/:/app/loadbalancer

networks:
  backend:
    internal: true
    ipam:
      config:
        - subnet: 192.168.4.0/24
          ip_range: 192.168.4.0/24
  external_network:
